# Generated by Django 2.1 on 2020-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200926_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
