# Generated by Django 2.1 on 2020-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200926_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
